[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_escrow = "145AeoxJYRT7MDomSmf4HJKf8BdZ7KQGF72D3DVrbwBq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
